name: Trigger Coze Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "52 6 * * *"

jobs:
  run-coze:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coze via curl
        run: |
          curl -X POST "https://api.coze.com/v1/workflow/run" \
            -H "Authorization: Bearer pat_rDYKlEuRVwkPuC3ATqfcOIuX1QJY6OjP5f8NVio60pdZvIDebsQXzkuRCm769S4b" \
            -H "Content-Type: application/json" \
            -d "{\"workflow_id\": \"7587434991573336069\", \"parameters\": {\"input\": \"Abidjan\"}}"
